.TH VHOSTGEN 1
.SH NAME
vhostgen - creates apache vhosts.conf using information taken from a mysql database
.SH SYNOPSIS
.B vhostgen
.SH
.PP
vhostgen fetches apache vhost information from a database and creates a vhost 
configuration file which can easily be included into the httpd.conf.

The database has to contain a table, which I chose to name "vhosts" (name
it whatever you want):

CREATE TABLE `vhosts` (
  `id` int(11) NOT NULL auto_increment,
  `servername` varchar(255) NOT NULL,
  `serveralias` varchar(255) default NULL,
  `documentroot` varchar(255) NOT NULL,
  `maintainer` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
);

.SH AUTHORS
Svante Kvarnstrom <sjk@ankeborg.nu>
